spring:
  application:
    name: ${SERVICE_NAME:em-adapter}

  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 16384                                                                       # Размер пакета сообщений в байтах
      acks: all                                                                               # Подтверждение всех реплик (все брокеры должны подтвердить запись сообщения)
      properties:
        enable.idempotence: true                                                              # Включаем идемпотентность (для предотвращения дублирования сообщений)
        max.in.flight.requests.per.connection: 5                                              # Максимальное количество запросов в очереди на одно соединение
        retries: 3                                                                            # Количество попыток повторной отправки сообщения в случае ошибки
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest                                                             # Сброс на самый старый offset при отсутствии состояния группы
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation.level: read_committed                                                       # Уровень изоляции для чтения (только подтвержденные изменения)


server:
  port: ${SERVER_PORT:8080}


management:
  server:
    port: ${ACTUATOR_PORT:8081}
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics,prometheus}                           # Список доступных эндпоинтов
  metrics:
    tags:
      application: ${spring.application.name}                                                   # Имя приложения для метрик
    distribution:
      percentiles-histogram:
        http.server.requests: true                                                              # Гистограмма для метрик HTTP-запросов
  tracing:
    sampling:
      probability: 1.0                                                                          # Трейсинг для всех запросов
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS_VISIBLE:always}                                            # Детализация информации о здоровье сервиса


eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_ENABLED:true}                                       # Регистрируем сервис в Eureka
    fetch-registry: ${EUREKA_FETCH_ENABLED:true}                                                # Загружаем список зарегистрированных сервисов
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://em-discovery:8761/eureka/}   # URL-адрес реестра Eureka
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}                                                # Используем хостнейм вместо IP
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:em-adapter}:${server.port}:${random.uuid}           # Уникальный идентификатор инстанса
    lease-renewal-interval-in-seconds: ${EUREKA_HEARTBEAT_INTERVAL:30}                          # Частота отправки heartbeat
    lease-expiration-duration-in-seconds: ${EUREKA_LEASE_EXPIRATION:90}                         # Время, через которое инстанс будет считаться недоступным
    status-page-url: http://${GATEWAY_PUBLIC_HOSTNAME:localhost}:${GATEWAY_PUBLIC_PORT:8080}/adapter/actuator
    health-check-url: http://${GATEWAY_PUBLIC_HOSTNAME:localhost}:${GATEWAY_PUBLIC_PORT:8080}/adapter/actuator/health


# Настройки повторных попыток
retry:
  max-retry-attempts: ${RETRY_MAX_ATTEMPTS:3}                                                   # Максимальное количество повторных попыток
  retry-interval-milliseconds: ${RETRY_INTERVAL:1000}                                           # Интервал повторных попыток в мс

# Топики Kafka
kafka:
  topic:
    consumer:
      collector-event: ${KAFKA_TOPIC_COLLECTOR_EVENT:gdelt-collector-event-topic}
      collector-mention: ${KAFKA_TOPIC_MENTION:gdelt-collector-mention-topic}
    producer:
      adapter-event: ${KAFKA_TOPIC_ADAPTER_EVENT:gdelt-adapter-event-topic}
      adapter-mention: ${KAFKA_TOPIC_ADAPTER_MENTION:gdelt-adapter-mention-topic}

# Конфигурация MinIO клиента
storage:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://minio:9000}                                                 # URL MinIO сервера (localhost для локального запуска)
    access-key: ${MINIO_ACCESS_KEY:eventmosaic}                                                   # Имя пользователя (из docker-compose)
    secret-key: ${MINIO_SECRET_KEY:eventmosaic}                                                   # Пароль (из docker-compose)
